import type { Locale } from '@/i18n/config';

/**
 * 隐私政策四语文案（docs/02 §9 合规清单：国际版按 GDPR/CCPA 标准，附数据流图）。
 * 放独立文件而不进 messages/*.json：政策文本自成一体（需要整体审阅/替换版本），
 * 不与界面文案共用命名空间。POLICY_VERSION（lib/consent.ts）实质修订时同步递增。
 */

export interface PrivacySection {
  title: string;
  paragraphs: string[];
}

export interface PrivacyText {
  title: string;
  updated: string;
  intro: string[];
  sections: PrivacySection[];
}

const en: PrivacyText = {
  title: 'Privacy Policy',
  updated: 'Last updated: September 2026 · Policy version 2026-09-v1',
  intro: [
    'This is a private space for your relationship with money. This policy explains, in plain language, what we collect, why, how long we keep it, and what you can do about it.',
    'The short version: your words belong to you. We never use them to train AI models, and you can export or delete everything at any time.',
  ],
  sections: [
    {
      title: 'What we collect',
      paragraphs: [
        'What you write into the product: your money-relationship check-up answers, what you say in conversations, journal entries, letters, notes on micro-actions, and childhood memories about money. Some of this — money troubles, psychological state, childhood memories — is sensitive by nature. That is exactly why we ask for your separate, explicit consent before generating your money portrait.',
        'Account data: if you create an account, your username, email address and password (stored only as a hash).',
        'Anonymous usage statistics: which features are used and when (e.g. "a journal entry was saved"), stored without any of your text.',
        'Consent records: when and whether you agreed to sensitive-data processing, with a timestamp, a hashed IP address and the policy version, so your choice is traceable.',
      ],
    },
    {
      title: 'How your data flows',
      paragraphs: [
        'Your device → our server → the AI model provider → back to your device. That is the whole journey of a sentence you write.',
        'The AI model provider processes your text solely to generate a response for you, under a zero-data-retention arrangement: it does not store your conversations, does not use them for training, and returns nothing to any third party.',
        'Our server logs contain only metadata (event names, counts), never the content of your conversations, journal or portrait.',
      ],
    },
    {
      title: 'How long we keep it',
      paragraphs: [
        'Your content is kept for as long as your account exists, so the companion can remember you across visits.',
        'If you delete your account, your data is removed from the live database immediately. Encrypted backups roll off within 30 days at the latest.',
      ],
    },
    {
      title: 'Your rights',
      paragraphs: [
        'Access and export: the "Me" page has a one-click export of everything — your portrait, conversations (full text), journal, letters and settings — as a JSON file.',
        'Deletion: the "Me" page also has account deletion. The live database is cleared immediately; backups roll off within 30 days. Deleting is self-service and takes effect without asking us.',
        'Consent: refusing the sensitive-data consent means no portrait is generated and no AI deep-talk happens — you can still use the questionnaire and journal.',
      ],
    },
    {
      title: 'Security',
      paragraphs: [
        'All traffic is encrypted in transit (TLS) and data is stored encrypted at rest. Your password is stored only as a salted hash; your recovery code is stored only as a hash, so even a database leak does not expose it.',
        'We do not sell your data and do not share it with advertising networks. There are no third-party tracking scripts on this site.',
      ],
    },
    {
      title: 'About AI, and about age',
      paragraphs: [
        'Everything the companion says is generated by an AI model. It offers company and reflection — it is not therapy, medical care, or financial advice.',
        'This product is for adults aged 18 and over. If you are in crisis or in danger, please contact your local emergency services or a local crisis hotline first.',
      ],
    },
    {
      title: 'Contact',
      paragraphs: [
        `Questions or requests about your data: ${process.env.SUPPORT_EMAIL ?? 'support contact will be published here'}. We aim to respond within 30 days.`,
      ],
    },
  ],
};

const zhCN: PrivacyText = {
  title: '隐私政策',
  updated: '最近更新：2026 年 9 月 · 政策版本 2026-09-v1',
  intro: [
    '这里是一个关于你和钱的关系的私密空间。这份政策用平实的话说明：我们收集什么、为什么、存多久，以及你可以做什么。',
    '一句话版本：你写下的每句话都属于你。我们绝不把它们用于训练 AI 模型；你随时可以导出或删除全部数据。',
  ],
  sections: [
    {
      title: '我们收集什么',
      paragraphs: [
        '你写进产品的内容：金钱关系体检的作答、对话里说的话、日记、信件、微行动记录，以及关于童年的金钱记忆。其中一部分——金钱困扰、心理状态、童年记忆——天然属于敏感信息。正因如此，在生成你的金钱画像之前，我们会单独、明确地征求你的同意。',
        '账号信息：如果你注册了账号，包括用户名、邮箱地址和密码（密码只以哈希形式存储）。',
        '匿名使用统计：哪些功能在什么时候被使用（例如「写下了一篇日记」），不包含你写的任何文字。',
        '同意记录：你是否同意处理敏感信息、发生在什么时间，带时间戳、IP 哈希和政策版本号，让你的选择可追溯。',
      ],
    },
    {
      title: '数据怎么流动',
      paragraphs: [
        '你的设备 → 本站服务器 → AI 模型服务商 → 回到你的设备。你写下的每句话，路径只有这一条。',
        '模型服务商只为给你生成回应而处理你的文字，按零数据保留约定接入：不存储你的对话、不用于训练、不提供给任何第三方。',
        '本站服务器日志只存元数据（事件名、次数），绝不存你的对话、日记或画像的原文。',
      ],
    },
    {
      title: '存多久',
      paragraphs: [
        '你的内容在账号存在期间一直保留——这是「它记得你」的前提。',
        '删除账号后，主库中的数据立即删除；加密备份最多 30 天内滚动清除。',
      ],
    },
    {
      title: '你的权利',
      paragraphs: [
        '访问与导出：「我的」页面有一键导出，把你的画像、对话（全文）、日记、信件和设置打包成一个 JSON 文件，只给你本人。',
        '删除：「我的」页面同样提供删除账号。主库即时清空，加密备份最多 30 天内滚动清除。删除是自助的，不需要向我们申请。',
        '同意：拒绝敏感信息同意的话，不会生成画像、也不会进行 AI 深谈——问卷和日记仍然照常可用。',
      ],
    },
    {
      title: '安全',
      paragraphs: [
        '传输全程 TLS 加密，存储静态加密。密码与恢复码都只存加盐哈希——即使数据库泄露，也还原不出你的密码或恢复码。',
        '我们不出售你的数据，也不向广告网络提供任何信息。本站没有第三方跟踪脚本。',
      ],
    },
    {
      title: '关于 AI，关于年龄',
      paragraphs: [
        '陪伴者说的每一句话都由 AI 模型生成。它提供的是陪伴与思考——不是心理治疗、医疗建议，也不是理财建议。',
        '本产品面向 18 周岁以上的成年人。如果你正处在危机或危险中，请先联系当地急救服务或心理援助热线。',
      ],
    },
    {
      title: '联系我们',
      paragraphs: [
        `关于你的数据的任何问题或请求：${process.env.SUPPORT_EMAIL ?? '支持联系方式即将公布'}。我们会在 30 天内回复。`,
      ],
    },
  ],
};

const zhTW: PrivacyText = {
  title: '隱私政策',
  updated: '最近更新：2026 年 9 月 · 政策版本 2026-09-v1',
  intro: [
    '這裡是一個關於你和錢的關係的私密空間。這份政策用平實的話說明：我們蒐集什麼、為什麼、存多久，以及你可以做什麼。',
    '一句話版本：你寫下的每句話都屬於你。我們絕不把它們用於訓練 AI 模型；你隨時可以匯出或刪除全部資料。',
  ],
  sections: [
    {
      title: '我們蒐集什麼',
      paragraphs: [
        '你寫進產品的內容：金錢關係體檢的作答、對話裡說的話、日記、信件、微行動紀錄，以及關於童年的金錢記憶。其中一部分——金錢困擾、心理狀態、童年記憶——天然屬於敏感資訊。正因如此，在生成你的金錢畫像之前，我們會單獨、明確地徵求你的同意。',
        '帳號資訊：如果你註冊了帳號，包括使用者名稱、信箱和密碼（密碼只以雜湊形式儲存）。',
        '匿名使用統計：哪些功能在什麼時候被使用（例如「寫下了一篇日記」），不包含你寫的任何文字。',
        '同意紀錄：你是否同意處理敏感資訊、發生在什麼時間，帶時間戳、IP 雜湊和政策版本號，讓你的選擇可追溯。',
      ],
    },
    {
      title: '資料怎麼流動',
      paragraphs: [
        '你的裝置 → 本站伺服器 → AI 模型服務商 → 回到你的裝置。你寫下的每句話，路徑只有這一條。',
        '模型服務商只為給你生成回應而處理你的文字，按零資料保留約定接入：不儲存你的對話、不用於訓練、不提供給任何第三方。',
        '本站伺服器日誌只存中繼資料（事件名、次數），絕不存你的對話、日記或畫像的原文。',
      ],
    },
    {
      title: '存多久',
      paragraphs: [
        '你的內容在帳號存在期間一直保留——這是「它記得你」的前提。',
        '刪除帳號後，主庫中的資料立即刪除；加密備份最多 30 天內滾動清除。',
      ],
    },
    {
      title: '你的權利',
      paragraphs: [
        '存取與匯出：「我的」頁面有一鍵匯出，把你的畫像、對話（全文）、日記、信件和設定打包成一個 JSON 檔案，只給你本人。',
        '刪除：「我的」頁面同樣提供刪除帳號。主庫即時清空，加密備份最多 30 天內滾動清除。刪除是自助的，不需要向我們申請。',
        '同意：拒絕敏感資訊同意的話，不會生成畫像、也不會進行 AI 深談——問卷和日記仍然照常可用。',
      ],
    },
    {
      title: '安全',
      paragraphs: [
        '傳輸全程 TLS 加密，儲存靜態加密。密碼與恢復碼都只存加鹽雜湊——即使資料庫外洩，也還原不出你的密碼或恢復碼。',
        '我們不出售你的資料，也不向廣告網路提供任何資訊。本站沒有第三方追蹤腳本。',
      ],
    },
    {
      title: '關於 AI，關於年齡',
      paragraphs: [
        '陪伴者說的每一句話都由 AI 模型生成。它提供的是陪伴與思考——不是心理治療、醫療建議，也不是理財建議。',
        '本產品面向 18 歲以上的成年人。如果你正處在危機或危險中，請先聯絡當地急救服務或心理援助專線。',
      ],
    },
    {
      title: '聯絡我們',
      paragraphs: [
        `關於你的資料的任何問題或請求：${process.env.SUPPORT_EMAIL ?? '支援聯絡方式即將公布'}。我們會在 30 天內回覆。`,
      ],
    },
  ],
};

const ja: PrivacyText = {
  title: 'プライバシーポリシー',
  updated: '最終更新：2026 年 9 月 · ポリシー版 2026-09-v1',
  intro: [
    'ここは、お金との関係に向き合うためのプライベートな空間です。このポリシーでは、何を収集し、なぜ収集し、どのくらい保管し、あなたは何ができるのかを、平易な言葉で説明します。',
    'ひとことで言えば：あなたの言葉はあなたのものです。AI モデルの学習に使うことは決してなく、いつでも書き出しも削除もできます。',
  ],
  sections: [
    {
      title: '収集するもの',
      paragraphs: [
        'あなたが製品に書き込んだ内容：お金との関係チェックの回答、対話の言葉、日記、手紙、小さな一歩の記録、そしてお金についての子ども時代の記憶。その一部——お金の悩み、心理状態、子ども時代の記憶——は、生まれつき敏感な情報です。だからこそ、お金の肖像を描く前に、私たちは別個の明確な同意をお願いしています。',
        'アカウント情報：アカウントを作成した場合のユーザー名、メールアドレス、パスワード（パスワードはハッシュのみ保存）。',
        '匿名の利用統計：どの機能がいつ使われたか（例「日記が一件書かれた」）。あなたのテキストは含まれません。',
        '同意の記録：敏感な情報の処理に同意したかどうかと、その時刻。タイムスタンプ、IP のハッシュ、ポリシー版とともに保存し、あなたの選択を追跡できるようにしています。',
      ],
    },
    {
      title: 'データの流れ',
      paragraphs: [
        'あなたのデバイス → 当サーバー → AI モデル提供元 → あなたのデバイスへ。あなたの言葉がたどる道は、この一本だけです。',
        'モデル提供元は、あなたへの応答を生成するためにだけテキストを処理し、ゼロデータリテンション（保持しない）の約束のもとで接続されています。対話を保存せず、学習に使わず、第三者に提供しません。',
        '当サーバーのログはメタデータ（イベント名や回数）のみで、対話・日記・肖像の本文は一切保存しません。',
      ],
    },
    {
      title: '保管期間',
      paragraphs: [
        'あなたの内容は、アカウントがある限り保管されます。それは「翌日もあなたを覚えている」ための前提です。',
        'アカウントを削除すると、稼働中のデータベースからは即時に削除されます。暗号化バックアップは遅くとも 30 日以内にローリングで消去されます。',
      ],
    },
    {
      title: 'あなたの権利',
      paragraphs: [
        'アクセスと書き出し：「自分」ページからワンクリックで、肖像・対話（全文）・日記・手紙・設定を JSON ファイルに書き出せます。受け取るのはあなただけです。',
        '削除：「自分」ページからアカウント削除もできます。稼働中のデータベースは即時に消去され、バックアップは 30 日以内に消えます。削除はセルフサービスで、申請は不要です。',
        '同意：敏感な情報への同意を拒否した場合は、肖像は生成されず、AI との深い対話も行われません。質問票と日記はそのまま使えます。',
      ],
    },
    {
      title: '安全対策',
      paragraphs: [
        '通信はすべて TLS で暗号化され、保存時も暗号化されています。パスワードとリカバリーコードは塩付きハッシュのみ保存——仮にデータベースが漏えても、元の値は復元できません。',
        'データを売却することはなく、広告ネットワークに提供することもありません。このサイトに第三者トラッキングのスクリプトはありません。',
      ],
    },
    {
      title: 'AI について、年齢について',
      paragraphs: [
        '伴走者の言葉は、すべて AI モデルが生成しています。提供するのは寄り添いと思考のお手伝いであり、心理療法・医療・投資助言ではありません。',
        '本製品は 18 歳以上の方向けです。いま危機にある、または危険が差し迫っている場合は、まず現地の緊急通報または相談ホットラインに連絡してください。',
      ],
    },
    {
      title: 'お問い合わせ',
      paragraphs: [
        `データに関するご質問・ご依頼：${process.env.SUPPORT_EMAIL ?? 'お問い合わせ先は後日ここに掲載します'}。30 日以内の返信を目指します。`,
      ],
    },
  ],
};

export const PRIVACY: Record<Locale, PrivacyText> = {
  en,
  'zh-CN': zhCN,
  'zh-TW': zhTW,
  ja,
};
